### ISSUE TITLE
Bad topic or filter provided

### ISSUE THREAD

**Issue by poli44** [mobizt/Firebase-ESP8266#104]
Hi,

lib 2.8.9
when I send first notification i get success 

{"message_id":7146077062196508237}

secendary try 

{"error":"InvalidParameters: Bad topic or filter provided"}

30 min after good and next bad topic or filter provided.

`
#include "FirebaseESP8266.h"
#include <ESP8266WiFi.h>

#define WIFI_SSID ""
#define WIFI_PASSWORD ""

#define FIREBASE_FCM_SERVER_KEY ""

FirebaseData firebaseData;

unsigned long lastTime = 0;

int count = 0;

void sendMessage();

void setup()
{

    Serial.begin(256000);

    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    Serial.print("Connecting to Wi-Fi");
    while (WiFi.status() != WL_CONNECTED)
    {
        Serial.print(".");
        delay(300);
    }
    Serial.println();
    Serial.print("Connected with IP: ");
    Serial.println(WiFi.localIP());
    Serial.println();
    firebaseData.fcm.begin(FIREBASE_FCM_SERVER_KEY);
    firebaseData.fcm.setPriority("high");
    firebaseData.fcm.setTimeToLive(1000);

}

void loop()
{

    if (millis() - lastTime > 10 * 1000)
    {
        lastTime = millis();

        sendMessage();
    }
}

void sendMessage()
{

    firebaseData.fcm.setNotifyMessage("a", "b");
    firebaseData.fcm.setTopic("TEST");
    if (Firebase.sendTopic(firebaseData))
    {
      Serial.println(firebaseData.fcm.getSendResult());
    }
    else
    {
      Serial.println("REASON: " + firebaseData.errorReason());
    } 
}`

13:02:44.209 -> Connected with IP: 192.168.77.47
13:02:44.209 -> 
13:02:54.067 -> {"message_id":4166644018461848267}
13:03:05.641 -> 
13:03:13.563 -> {"error":"InvalidParameters: Bad topic or filter provided"}
13:03:23.578 -> {"error":"InvalidParameters: Bad topic or filter provided"}
13:03:33.592 -> {"error":"InvalidParameters: Bad topic or filter provided"}
13:03:43.538 -> {"error":"InvalidParameters: Bad topic or filter provided"}
13:03:53.416 -> {"error":"InvalidParameters: Bad topic or filter provided"}

**Comment by mobizt** [comment]
Thanks for inform this issue.

I update the library and this issue fixed already, please update (from Github).
