### ISSUE TITLE
HELP how to detect there is not internet avaliable?

### ISSUE THREAD

**Issue by danilomna** [mobizt/Firebase-ESP8266#108]
Hi @mobizt, 

I´m using the streaming example of yout library, it is a awesome job, congratulations one more time.

the ESP8266 can detect when WiFi signal is cut off, no issue on that, but I have an issue when just the internet signal is gone but WiFI remains.

How to detect we have no internet?? (if we still have WiFi signal)

Please, any help would be very appreciated.

best regards, 
Danilo

**Comment by mobizt** [comment]
Test the server connection e.g. google.com using http client or WiFi client by provide the response waiting timeout.

If no response returns within the specific time, that's the internet connection issue.
