### ISSUE TITLE
HELP Firebase disconnection info or trigger

### ISSUE THREAD

**Issue by danilomna** [mobizt/Firebase-ESP8266#109]
Hi @mobizt , 

First of all thanks for answer my previous question, I´ll try to do like you suggested.

I have one more doubt, now from the Firebase server side, maybe you can help.

lets say a device is connected to firebase using streaming (like in your exemple) and internect signal is cut, lost.
Are there some way to know in Firebase this connection was lost? to trigger maybe a function and informe user the device is not avaliable?? 
This is would be use do inform status online and offline of a device in users app, maybe send a notification to user saying device is offline.
How to detect disconnection on Firebase side?

Any help, idea would be very appreciated.

best regards, 
Danilo

**Comment by mobizt** [comment]
Please read [this issue #102](https://github.com/mobizt/Firebase-ESP8266/issues/102).
