### ISSUE TITLE
getInt returning  incorrect values

### ISSUE THREAD

**Issue by jibin2706** [mobizt/Firebase-ESP8266#11]
I tried retrieving integer values using 
getInt but it is returning 1 no matter what the value is in the database.

long int test2 = Firebase.getInt(firebaseData, "/parking/1000/spot1/validTill");

**Comment by mobizt** [comment]
My library has difference API interfaces from other Firebase libraries or from FirebaseExtended user. 
Please see examples in examples folder and read me page.

You need to modify your existing code to match this library's API.

**Comment by mobizt** [comment]
You can start from here https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino

**Comment by jibin2706** [comment]
> You can start from here https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino
Solved
Thanks a lot for this awesome library
