### ISSUE TITLE
Timestamp as Node Name

### ISSUE THREAD

**Issue by CaioFPeres** [mobizt/Firebase-ESP8266#118]
Hello, i have read all the docs but couldn't figure out how can i get the timestamp, or set as Node/folder name, for organization purposes.

What i want to achieve is something like this:

[Example](https://i.imgur.com/38A7GmT.png)

Doesn't necessarily needs to have another timestamp inside node.

Is it possible to do it? Thanks is advance!

**Comment by mobizt** [comment]
Sorry I don't understand your question.

Please try the [examples](https://github.com/mobizt/Firebase-ESP8266/tree/master/examples) first for how to use.

**Comment by CaioFPeres** [comment]
I would like to set the timestamp on the path.
Something like this:

Firebase.setInt(firebaseData, "Anything/" + Timestamp + "/Variable", variable);

**Comment by mobizt** [comment]
What is the type of Timestamp? Number or string?
If it is number you should make it as  string.

**Firebase.setInt(firebaseData, "Anything/" + String(Timestamp) + "/Variable", variable);**

**Comment by CaioFPeres** [comment]
Ok, but how can i get it from firebase servers? I need this timestamp but dont know how to get it. 

In javascript, there is a function called firebase.database.ServerValue.TIMESTAMP which i can assign to a variable, like this:

timestamp = firebase.database.ServerValue.TIMESTAMP;

and then i could set to the path name. How can i do the same using the library?

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Timestamp/Timestamp.ino

**Comment by CaioFPeres** [comment]
I understand now, thank you.
