### ISSUE TITLE
Issue when stream multiple paths with large data

### ISSUE THREAD

**Issue by wathui99** [mobizt/Firebase-ESP8266#121]
I got issue when streaming with large data. There is nothing received. But, it worked fine if I following these steps:
1. delete some data of the tree
2. begin streaming
3. add deleted data back
After these steps, I received data when it change perfectly.

Is there any solution to solve this issue without delete data firstly?

This is my code:
setBSSLBufferSize(1024, 1024);
setResponseSize(1024);
beginMultiPathStream(...);

**Comment by mobizt** [comment]
Try to increase rx buffer more e.g.
setBSSLBufferSize(more value, 1024);
setResponseSize(more value);

You may need to redesign your database to separate the small data that being monitor (listening) out of the large static data.

Listen to large data change is impossible in device that has only < 50k ram.
