### ISSUE TITLE
HELP NEEDED QUESTION

### ISSUE THREAD

**Issue by rajmohanjena** [mobizt/Firebase-ESP8266#122]
Sir if we can have a feature in the library to create and call a function when the nodemcu/esp8266 doesnt connect to the internet. It would be great. I am not sure if this is available, kindly make me aware of it.
For EX- We can use it in projects like in terms of Home Automation Systems when the internet is not available we can check it and call a function within which the relays will be directly be controlled from the pins which are connected to other pins through switches..

**Comment by mobizt** [comment]
@rajmohanjena What is your issue?

**Comment by rajmohanjena** [comment]
Sir if we can have a feature in the library to create and call a function when the nodemcu/esp8266 doesnt connect to the internet. It would be great. I am not sure if this is available, kindly make me aware of it.
For EX- We can use it in projects like in terms of Home Automation Systems when the internet is not available we can check it and call a function within which the relays will be directly be controlled from the pins which are connected to other pins through switches..

**Comment by mobizt** [comment]
The library provides the error checking which includes server connection error and all server responses errors.

You can check the example and test what's the **firebaseData.errorReason()** returns when the internet connection was disconnected.

**Comment by mobizt** [comment]
You also get the http code (number) from server when call the functions with **firebaseData.httpCode()**.

When you call the functions e.g. get, set, push and delete, the http code should be 200 for success operation.

To add additional feature about the internet connection status requires http client to work and use more memory. 

If we use the Firebase Data object to check the server connection status, it will interrupt the stream connection if we use that Firebase Data object for stream too.

That is why that feature is not implemented.
