### ISSUE TITLE
Firebase reading 

### ISSUE THREAD

**Issue by jorgele** [mobizt/Firebase-ESP8266#124]
Hi. I am designing a system that must have two-way communication with firebase. It is very simple to write to my database, but it is not practical for me to make periodic readings to obtain the stored data. By doing this, I eventually get an error, or worse, my system resets. Is there a way to know if the database has been modified, so that I can read it, or a way to monitor a value in real time? I am using a Wemos D1 mini. Thank you very much.

**Comment by mobizt** [comment]
This [example](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Stream_callback/Stream_callback.ino) and [this](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Stream/Stream.ino) are what you're looking for.

Please read through the README for how to use that feature.
