### ISSUE TITLE
Q?: Recommended rules for Firebase 

### ISSUE THREAD

**Issue by worthapenny** [mobizt/Firebase-ESP8266#128]
Hey guys,

Thanks much for the beautiful library!

I am wondering if you guys have some recommendations on rules that can be in place on the DB side.

I currently have this:
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
} 
```

... which obviously isn't secure. Any suggestions?

**Comment by mobizt** [comment]
You can set read and write rules to be any i.e. true or false or any condition because the library uses database secret for authentication and the read and write rules will be ignored.

**Comment by worthapenny** [comment]
@mobizt Thanks for the speedy response! In that case, (a general question while I got you here), I feel little uncomfortable putting the FIREBASE_HOST and the FIREBASE_AUTH in plain text as I plan to share my project with my non-tech buddies. So, I will have the ESP8266 preprogrammed but still wondering if there is a way to encrypt the host and auth information.

**Comment by mobizt** [comment]
Firebase authentication required these information  i.e project url and access token or database secret (used in this library).

No matter what you're program in any platform e.g. android, iOS, web (javascript), Java, theses information always required in source code and you can't ignore or hide them.

**Comment by mobizt** [comment]
You can use base64 encode and decode.

You give them the encoded string of host and auth and you need to implement the code to decode on your buddy sketch. 

https://techtutorialsx.com/2017/12/09/esp32-arduino-base64-enconding/

**Comment by mobizt** [comment]
The **auth** in database rules i.e. **".read": "auth != null"** is the access token which ESP8266 does not has the memory and tool (SSL/TLS library) that can make these token unless ESP32 can do.
