### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by enigma0503** [mobizt/Firebase-ESP8266#129]
I am running the example sketch named "Beginner_start_here"; but I'm getting the following error on my serial monitor:

Error in setInt, unauthorized, Could not parse auth token.
Error in getInt, unauthorized, Could not parse auth token.
Error in get, unauthorized, Could not parse auth token.

![Screenshot (381)](https://user-images.githubusercontent.com/22156404/90133307-dbbd5600-dd8c-11ea-875e-1b5ee6e0abeb.png)

**Comment by mobizt** [comment]
Did you change [this](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Beginner_start_here/Beginner_start_here.ino#L21) with your database secret?

**Comment by enigma0503** [comment]
Yes, I've replaced that with my url and the corresponding key. Also, read and write rules in firebase are set to "true"

**Comment by mobizt** [comment]
The error returned from Firebase server which means the **FIREBASE_AUTH** you provided is not valid.

You should copy it from  the console as in the image below.

![1_t2KhKAQ2v-6oTAbq5CeBrw](https://user-images.githubusercontent.com/16171979/90138128-bb979200-dda0-11ea-907b-272868581595.png)
