### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by milinddhanke** [mobizt/Firebase-ESP8266#132]
Please help, something has changed in google firebase, my realtime data is disappear and database secrete is also have problem. 
This is massage  "Unable to load the database secrets"

**Comment by mobizt** [comment]
Firebase service is online normally.

Check your internet connection and you may delete your web browser cache or use other web browsers to sign in or use your other google/gmail  accounts to sign in or create new project.

**Comment by milinddhanke** [comment]
Thank you, I test it using other operator internet like Airtel, Vodaphone, BSNL (India), But it is not working with JIO (India) network.
Any Suggestion.

**Comment by mobizt** [comment]
Ask Google representative on your country or Firebase Facebook page.

**Comment by milinddhanke** [comment]
ok, Thanks

**Comment by milinddhanke** [comment]
As per your suggestion i mail to google firebase, and replied as follows!!!!!!!!!!!!

My name is Jonathan, thanks for reaching out.

 
We've seen multiple reports about similar issues, and from what we have found so far is that this is very likely a network issue, related to the internet provider.

 
Now, one user reported a DNS error, so one thing to try is using public DNS servers to verify if this is the issue. For example, from Google, you can use these: 8.8.8.8 and 8.8.4.4 (click here for more details).

 
Finally, if that confirms it, what I suggest is to open the browser's developers tools and to gather the logs from the "Network" tab when you go to the Database Dashboard and get in touch with your provider to ask about this. I'll check the team to see what we can do, but getting in touch with the provider looks like the best option at this moment.

 
So, let me know how it goes, and feel free to reach out with any further questions.


Kind regards,

Jonathan

Any comment from your side??????????

**Comment by mobizt** [comment]
Did you try it? I mean set up your PC network adapter to use DNS.

Can you go to Firebase console (website)? If yes, and you still get the problem in getting the information from console, you may browsing through the proxy server/gateway which you need to contact your ISP.
