### ISSUE TITLE
How to read realtime data from Firebase???

### ISSUE THREAD

**Issue by overing1314** [mobizt/Firebase-ESP8266#14]
Can someone help me? I want to set a condition that the LED going to TURN ON when detecting "1" from the real-time database of Firebase, and TURN OFF when detecting "0" from the real-time database of Firebase. Here is my coding....

#include "FirebaseESP8266.h"
#include <ESP8266WiFi.h>

#define FIREBASE_HOST xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define FIREBASE_AUTH "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define WIFI_SSID "SDIP"
#define WIFI_PASSWORD "11111111"

FirebaseData firebaseData;

String path = "STATUS_1";

void setup()
{
  Serial.begin(9600);
  
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  Firebase.reconnectWiFi(true);
  pinMode(D5,OUTPUT);

}
int n=0;

void loop()
{
 Firebase.getInt(firebaseData, path , n));
 if( n==1)
 {
      Serial.println("ALARM ON");
      digitalWrite(D5,HIGH);
  }
  else
  if(n==0)
  {
      Serial.println("ALARM OFF");
      digitalWrite(D5,LOW);
  }
 }

 
![11111111](https://user-images.githubusercontent.com/36887809/56503059-16bbca80-6547-11e9-917b-692e51f10d79.png)

**Comment by ntgussoni** [comment]
You can check the Stream Example
https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Stream/Stream.ino
