### ISSUE TITLE
Not getting data from the parentnode

### ISSUE THREAD

**Issue by lchvsanilkumar** [mobizt/Firebase-ESP8266#140]
Hi sir,I am using multipath streaming example to get data from firebase.but I can't get data from the parentnode...I will getting data from the childnodes while using  the multipath streaming...I didn't getting the value from the parent node......thank you...

**Comment by mobizt** [comment]
Please read [this](https://github.com/mobizt/Firebase-ESP8266/issues/139#issuecomment-694314943), it designed to get the children not a whole parent, it you want that use normal stream instead.
