### ISSUE TITLE
help need

### ISSUE THREAD

**Issue by lchvsanilkumar** [mobizt/Firebase-ESP8266#144]
sir, i need to push data "\"Fan\"" like in this format..how can i push this data in this format...please tell me sir...

**Comment by mobizt** [comment]
Use the back slash which followed by double quote to make a escape sequence like this.
![Untitled](https://user-images.githubusercontent.com/16171979/94249670-6a0b2700-ff4a-11ea-8ab8-eeedc5f82f93.png)

**Comment by lchvsanilkumar** [comment]
sir i can't push data like that format to firebase even i followed you suggetion...
so ,if you don't mind 
    if (Firebase.set(firebaseData2, parentPath + "/node2/new/data", "\"\"fan\"\"))
 please correct this line where it need...thank you sir

**Comment by mobizt** [comment]
I don't understand what you do.
Why you need double quote in double quote like this ""Fan""? It's so strange. 

If the GitHub auto format what you are trying to post here, please use the capture image instead.

**Comment by mobizt** [comment]
If you want to do so.
![Untitled](https://user-images.githubusercontent.com/16171979/94276208-1e6c7380-ff72-11ea-8380-5f44a8c775a6.png)

Please search google for the **escape sequence**.

**Comment by lchvsanilkumar** [comment]
Set string...
FAILED
REASON: bad request, Invalid data; couldn't parse JSON object, array, or value..
i am getting error like this

**Comment by mobizt** [comment]
Firebase is not support nested double quote.
You can test this in the web console.
