### ISSUE TITLE
Firebase Cloud Messaging is not working

### ISSUE THREAD

**Issue by gelsenchop** [mobizt/Firebase-ESP8266#152]
If you use the Firebase Cloud Messaging (FCM) function, you will not get a response from the client.
I made the following change in the FirebaseESP8266 file:

The instructions
7359 httpcode = net.sendRequest (header, "");
7360 httpcode = net.sendRequest (msg, "");

by the following replacement

httpcode = net.sendRequest (header, msg);

Then runs.

**Comment by mobizt** [comment]
Thanks for inform but the return value is not actually httpcode (returns true for success or false for failed) and need to change.

This is not bug or affected to the operation as if the header success to send, the payload should success too.

The esp8266 code need to be rewrite in the same way as esp32 which handles better header and payload.
