### ISSUE TITLE
Not using semantic versions?

### ISSUE THREAD

**Issue by doublejosh** [mobizt/Firebase-ESP8266#158]
The release numbering looks like this repo doesn't use normal [semantic versioning](https://semver.org)... and is instead just counting from 1 to 9 for each digit?!? https://github.com/mobizt/Firebase-ESP8266/releases

Did you mean for this release to be 2.9.10?
Are there actual breaking changes in 3.0.1?
Did you intend to skip 3.0.0?

Don't put dots in your releases names if they don't mean anything.

**Comment by mobizt** [comment]
Do yo have problem with this?

Don't open the issue just about this.

The versioning is up to the dev not up to somebody or systems.
