### ISSUE TITLE
SD Card mount failed

### ISSUE THREAD

**Issue by Ishara-Lakshan** [mobizt/Firebase-ESP8266#16]
I mounted my SD card module to NodeMcu as follows
Gnd > gnd
Vcc > 3v3
Cs > D2
Sck > D5
Mosi > D6
Miso > D7
When i uplaod the code and open the serial monitor an error message appears saying "SD Card mounted failed". Is there anything wrong in my connection with SD card module and NodeMcu? 
Thank you.

**Comment by mobizt** [comment]
Here is the default configuration

NodeMCU > SD

D5---------> SCK
D6---------> MISO
D7---------> MOSI
D8---------> CS

**Comment by Ishara-Lakshan** [comment]
Tried connecting this way...but still the error message appears.

**Comment by mobizt** [comment]
My library use core ESP8266 SPI library.
This may be SD card, SD module and wrong connection problems.

Try basic example in Arduino IDE  to test read or write simple text file to SD card.

**Comment by Ishara-Lakshan** [comment]
Ok I'll try it. Thank you

**Comment by mobizt** [comment]
Or try to include SPI.h in your sketch.

**Comment by Ishara-Lakshan** [comment]
SPI.h is already included
