### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by riskiadi** [mobizt/Firebase-ESP8266#161]
**I cant push with a long value (timestamp).**

FirebaseJson json1;
json1.set("Hi/myInt", 1204015873253);
Firebase.pushJSON(firebaseData, "visitors", json1);

c:/users/alkalynx/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\Smart-Doorbell.ino.cpp.o: in function `setup':
C:\Users\Alkalynx\Desktop\Smart-Doorbell/Smart-Doorbell.ino:58: undefined reference to `bool FirebaseJson::set<unsigned long>(String const&, unsigned long)'
c:/users/alkalynx/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\Smart-Doorbell.ino.cpp.o: in function `sendNotification()':
C:\Users\Alkalynx\Desktop\Smart-Doorbell/Smart-Doorbell.ino:100: undefined reference to `bool FirebaseJson::set<unsigned long>(String const&, unsigned long)'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
 Used: C:\Users\Alkalynx\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by mobizt** [comment]
The long data type is not supported use double instead and cast to your long variable when get the data back from the Firebase or JSON object.
