### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jatu-studiobox** [mobizt/Firebase-ESP8266#162]
**Use "setTimestamp" function. Timestamp Data result was set in Realtime Database, but function return "false" and the error is "data type mismatch".**

1. I use ESP8266 core 2.7.4 in Arduino IDE.
2. I installed "Firebase ESP8266 Client" version 3.0.1. 
3. I use Firebase ESP8266 Client "timestamp" example in Arduino IDE.
4. I changed connection variables in example source code for my WiFi and Firebase Realtime Database.
5. Upload example to my NodeMCU 12-E ESP8266.
6. Open Serial Monitor in Arduino IDE.
7. I see the error in Serial Monitor below
![screen1](https://user-images.githubusercontent.com/43282496/98016895-19cc9200-1e31-11eb-97e2-cf884f25bc83.png)
8. I was checked data in my Realtime Database. Timestamp Data result was set in Realtime Database.
![screen2](https://user-images.githubusercontent.com/43282496/98017188-7d56bf80-1e31-11eb-8b57-3603ff7de378.png)
9. Below is part of example source code, that use "setTimestamp" but the result setTimestamp function is false and display error.
![screen3](https://user-images.githubusercontent.com/43282496/98017633-1ab1f380-1e32-11eb-936a-e0846a7a56e7.png)

**IDE and its version:**
 - Arduino Version 1.8.13.

**ESP8266 Arduino Core SDK version**
 - 2.7.4

**Comment by mobizt** [comment]
This issue is now fixed. Please update the library to v3.0.2 (via GitHub download).
