### ISSUE TITLE
SUGGESTION DOI or other way to cite this library

### ISSUE THREAD

**Issue by ChrisGy** [mobizt/Firebase-ESP8266#171]
How can this library be cited in a research paper? Can DOIs and or zenodo archives be provided at least for major releases?

**Comment by mobizt** [comment]
Thanks for suggestion. I will notify you when the library update is ready and I have completed the zenodo setup.

**Comment by mobizt** [comment]
Now DOI is available.
Link on the badge on README.

**Comment by ChrisGy** [comment]
> Now DOI is available.
> Link on the badge on README.

This is great. Thanks a lot.
