### ISSUE TITLE
How to connect esp8266 with Wi-Fi

### ISSUE THREAD

**Issue by Paweena1997** [mobizt/Firebase-ESP8266#181]
![How to 1](https://user-images.githubusercontent.com/74338592/104104319-daf80400-52d9-11eb-85fa-547606830eb9.jpg)

**Comment by mobizt** [comment]
Please clarify your question.

I don't know what do you mean.

This is Firebase library.

**Comment by Paweena1997** [comment]
what caused this problem

**Comment by mobizt** [comment]
I don't know what's your problem.

**Comment by mobizt** [comment]
Your question is **How to connect esp8266 with Wi-Fi** and nothing related to the library.

**Comment by Paweena1997** [comment]
l can not connect esp8266 with Wi-Fi

**Comment by mobizt** [comment]
It's not related to the library. 
You can search google how to connect the WiFi instead of open the issue here.

**Comment by Paweena1997** [comment]
l using your library but can not connect

**Comment by mobizt** [comment]
Your question is not clear.

Post your code here and paste all error message here.

**Comment by mobizt** [comment]
You must provide more info when asking someone help because nobody know your code.

**Comment by Paweena1997** [comment]
will say  cry .
you have faccebook.

**Comment by Paweena1997** [comment]
Don't know how to tell

**Comment by mobizt** [comment]
I see. Are you from India or Thailand?

You can send your code and error message to Email k_suwatchai@hotmail.com.

Actually I'm not convenient to use Email to support anyone.

**Comment by Paweena1997** [comment]
l am connecteed error

**Comment by Paweena1997** [comment]
คือสาเหตุมันเป็นแบบนี้คือไม่สามารถเชื่อมต่อกับFirebaseได้คืออยากทราบว่าเป็นที่อะไร

**Comment by mobizt** [comment]
You need to post your code and error message that printed on the serial here.
I can't help without your code.
