### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lchvsanilkumar** [mobizt/Firebase-ESP8266#184]
Hello sir, I want to pause firebase while internet is down because of I need to run another loop and when the internet is available ,continue the firebas e operation....(wifi is always available)....please help sir

**Comment by mobizt** [comment]
You can use [pauseFirebase](https://github.com/mobizt/Firebase-ESP8266/tree/master/src#pauseunpause-wificlient-from-all-firebase-operations) function of the FirebaseData object.

Example, if your FirebaseData object dedined as fbdo.

```cpp
//To pause,
fbdo.pauseFirebase(true);

//To unpause,
fbdo.pauseFirebase(false);
```

After you pause the Firebase data, the http session will be terminated and the memory used by the internal SSL client will be released.

**Comment by lchvsanilkumar** [comment]
Thank you ,I will try
