### ISSUE TITLE
HELP Is it possible to pause/end the connection to Firebase?

### ISSUE THREAD

**Issue by bmarcu13** [mobizt/Firebase-ESP8266#188]
I am trying to get a url from my RTDB and then use that to download some image from that url. 
Because (I'm guessing here) the Firebase connection is running, the connection to the url I fetched is failing. 
Is it possible to pause/end the connection to firebase until I finish downloading my images and then restart it again?

**Comment by mobizt** [comment]
Call the pauseFirebase from the Firebase Data object like this

```cpp
fbdo.pauseFirebase(true); //To pause (stop)

fbdo.pauseFirebase(false); //To unpause 
```
