### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by HaHiep** [mobizt/Firebase-ESP8266#189]
Hello and thank you for this library!
I want to push data Json
 from api openweathermap to firebase can you help me how can I do that?
Thanks!
![Screenshot (48)](https://user-images.githubusercontent.com/56423478/108672044-fb8bbe80-7513-11eb-800e-7b3e92694e38.png)

**Comment by mobizt** [comment]
I don't know but you can look at the [examples](https://github.com/mobizt/Firebase-ESP8266/tree/master/examples) and test and adapt yourself.
