### ISSUE TITLE
connection Refused if use ESP-NOW

### ISSUE THREAD

**Issue by dadingfs** [mobizt/Firebase-ESP8266#190]
![image](https://user-images.githubusercontent.com/43590820/108764073-b3f14b00-7584-11eb-9327-2031933b799b.png)
when i want to get data form firebase if i get data form another esp with ESP-NOW but when get data it say connection Refused. if not use ESP-NOW it will work normal
it's my code
`#include <Arduino.h>
#define output 14
//RTC
#include <DS3231.h>
RTClib myRTC;
int tahun()
{
  DateTime now = myRTC.now();
  Serial.print(now.year(), DEC);
  return now.year();
}
int bulan()
{
  DateTime now = myRTC.now();
  Serial.print(now.month(), DEC);
  return now.month();
}
int hari()
{
  DateTime now = myRTC.now();
  Serial.print(now.day(), DEC);
  return now.day();
}
int jam()
{
  DateTime now = myRTC.now();
  Serial.print(now.hour(), DEC);
  return now.hour();
}
//Firebase
#include <FirebaseESP8266.h>
#define FIREBASE_HOST "****"
#define FIREBASE_AUTH "****"
FirebaseData fbdo;
FirebaseAuth auth;
FirebaseConfig config;
String getData(String path)
{
  if (Firebase.getString(fbdo, path))
  {
    Serial.print("Sukses mengambil data, data = ");
    Serial.println(fbdo.stringData());
    return fbdo.stringData();
  }
  else
  {

    Serial.print("Gagal mengambil data, ");
    Serial.println(fbdo.errorReason());
    return "Tidak ada data";
  }
}

//WIFI
#include <ESP8266WiFi.h>
#define WIFI_SSID "****"
#define WIFI_PASSWORD "****"
void InitWiFi()
{
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Menyambung ke WiFi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print("-");
    delay(300);
  }
  Serial.println();
  Serial.print("Tersambung dengan IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();
}
//ESPNOW
#include <espnow.h>
typedef struct struct_message
{
  char QR[250];
} struct_message;
struct_message myQR;
void OnDataRecv(uint8_t *mac, uint8_t *incomingData, uint8_t len)
{
  memcpy(&myQR, incomingData, sizeof(myQR));
  char data[250]="Tidak Terbaca";
  if (myQR.QR == data)
  {
    String nama;
    String nim;
    String enc;
    String code;
    Serial.print("Bytes received: ");
    Serial.println(len);
    Serial.print("Data : ");
    Serial.println(myQR.QR);
    Serial.println();
    nama=String(hari())+"-"+String(bulan())+"-"+String(tahun())+"/"+String(jam())+"/NAMA";
    nim=String(hari())+"-"+String(bulan())+"-"+String(tahun())+"/"+String(jam())+"/NIM";
    enc=String(hari())+"-"+String(bulan())+"-"+String(tahun())+"/"+String(jam())+"/encryption";
    getData(nama);
    getData(nim);
    code=getData(enc);
    if (myQR.QR == code.c_str()){
      digitalWrite(output, HIGH);
    }
  }
  else
  {
    Serial.print("Tidak ada code QR");
    Serial.println();
    getData("LED_Status");
  }
}

void setup()
{
  Serial.begin(115200);
  pinMode(output,OUTPUT);
  Wire.begin();
  WiFi.mode(WIFI_AP_STA);
  InitWiFi();
  Serial.print("Login ke Firebase");
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  //Firebase.reconnectWiFi(true);
  Serial.print("Sukses");
  Serial.println();
  Serial.print("Mulai menerima data");

  if (esp_now_init() != 0)
  {
    Serial.println("Error initializing ESP-NOW");
    return;
  }

  esp_now_set_self_role(ESP_NOW_ROLE_SLAVE);
  esp_now_register_recv_cb(OnDataRecv);
}

void loop()
{
}`

**Comment by mobizt** [comment]
Did you success uing ESP now with WiFi?
Did you ever google or test it before?

It's not a library issue.
