### ISSUE TITLE
Compile Error; Multiple libraries were found for "SD.h"

### ISSUE THREAD

**Issue by orewayaya** [mobizt/Firebase-ESP8266#199]
Multiple libraries were found for "SD.h"
In file included from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/common.h:45:0,
 Used: C:\Users\yaya\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/Utils.h:37,
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/signer/Signer.h:37,
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/FirebaseESP8266.h:53,
                 from C:\Users\yaya\AppData\Local\Temp\arduino_modified_sketch_214887\Basic.ino:18:
C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/wcs/esp8266/FB_HTTPClient.h:67:22: fatal error: LittleFS.h: No such file or directory
 #include <LittleFS.h>
                      ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

====================================================================================

after deleting the SD folder >>

In file included from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/common.h:45:0,
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/Utils.h:37,
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/signer/Signer.h:37,
                 from C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/FirebaseESP8266.h:53,
                 from C:\Users\yaya\AppData\Local\Temp\arduino_modified_sketch_720985\Basic.ino:18:
C:\Users\yaya\Documents\Arduino\libraries\Firebase-ESP8266-master\src/wcs/esp8266/FB_HTTPClient.h:67:22: fatal error: LittleFS.h: No such file or directory
 #include <LittleFS.h>
                      ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

help tq ._.

**Comment by mobizt** [comment]
You should install the ESP8266 Arduino Core SDK. 

Follow [this instruction](https://github.com/esp8266/Arduino#installing-with-boards-manager) for installation.

If you're already installed, your SDK may be outdated, you need to update to v2.7.4.

ESP8266 Arduino Core SDK v3.0.0 is not recommended at this time [due to this](https://github.com/mobizt/Firebase-ESP8266#important-information).
