### ISSUE TITLE
push json limits

### ISSUE THREAD

**Issue by blotfi** [mobizt/Firebase-ESP8266#2]
Hi and thank you for this library
It works well but if I want to push this json it doesn't work
{
  "name": "iot4",
  "datetime": "2019/03/22 11:27:59",
  "accelX": 0.067871,
  "accelY": -0.026367,
  "accelZ": -0.928223,
  "temp": 26.65,
  "humid": 93248.09
}
whereas if I put less numbers after the decimal point or less numbers (0 instead of 93248.0) , it works
Is there a buffer I can increase somewhere?
thanks

**Comment by mobizt** [comment]
First, try to edit library in [this issue](https://github.com/mobizt/Firebase-ESP8266/issues/1#issuecomment-475478225).
Try to push this string

```C++

String json = "{\"name\":\"iot4\",\"datetime\": \"2019/03/22 11\:27\:59\",\"accelX\": 0.067871,\"accelY\": -0.026367,\"accelZ\":-0.928223,\"temp\": 26.65,\"humid\": 93248.09}";

```

It should ok. If it's ok, check how you create json string e.g. from ArduinoJson object using printTo or create as string as above string.

Not recommend to include colon (:) i.e. 11:27:59 in database because it used as key/value separator in json object.  I use escape character, back slash before colon (\:) to make it can parse as :

**Comment by blotfi** [comment]
I use doc Arduinojson it is not a problem.
As I said I can send it if there is less characters
There is a limitation somewhere I need to bypass

**Comment by mobizt** [comment]
My library send string as payload to server without any modification as I ask you to send json string  of above post. If it works, the problem is in json object you create. You need to check the value you add to root and read it back.

**Comment by mobizt** [comment]
Can you show example code for me to test?

**Comment by blotfi** [comment]
Ok but when I will be in front of my computer later

**Comment by blotfi** [comment]
I mean instead of doing
`char output[128];
	serializeJson(doc, output);
  Firebase.pushJSON(firebaseData, "/data", output);
}`

**Comment by mobizt** [comment]
You need to assign macho ARDUINOJSON_USE_DOUBLE  before include ArduinoJson.h like this

```C++

#define ARDUINOJSON_USE_DOUBLE 1
#include <ArduinoJson.h>

```
Here is the example to test

Try to push json data

```C++

DynamicJsonDocument doc(256);
double val1 = -0.00000001; //max 8 decimal places
double val2 = 321.12345678; //max 8 decimal places
doc["val1"] = val1;
doc["val2"] = val2;

char output[128];
memset(output, 0, 128);
serializeJson(doc, output);
Firebase.pushJSON(firebaseData, "/data", output);
```

Try to read json data back
```C++
Firebase.getJSON(firebaseData, "/data");

DynamicJsonDocument _doc(256);
deserializeJson(_doc, firebaseData.jsonData());
double _val1 = _doc["val1"];
double _val2 = _doc["val2"];
Serial.println(_val1,8);
Serial.println(_val2,8);
```

**Comment by blotfi** [comment]
It seems that you did not understood me or that I didn't explain well.
Everything is working fine, it was my fault 
`char output[128];`
is not enough
`char output[150];`
is ok

I just asked if there is another way instead of going through a fixed buffer, perhaps using String

**Comment by mobizt** [comment]
I know as much as information you provide, the only part of your incompleted code then I need to build the basic test and extend the possibility to handle maximum decimal places for ArduinoJSON. 

For String object it can because it has write function that ArduinoJson used for modify string.

```C++
String output="";
serializeJson(doc, output);

```

**Comment by blotfi** [comment]
thanks

**Comment by Proxcentaur** [comment]
I got this error when I was trying to put that code:
no matching function for call to 'FirebaseESP32::pushJSON(FirebaseData&, StringSumHelper&, ArduinoJson::JsonObject&)'

**Comment by mobizt** [comment]
@Proxcentaur The library APIs were changed sofar. 

You need to provide the FirebaseJson object to the pushJSON function.

For example.

```C++
FirebaseJson json;

json.add("data1",100); //add (new) data
json.set("data2/new", "test"); //set (replace or create new) the data

Firebase.pushJSON(firebaseData, "your_node_path", json);
```

**Comment by Proxcentaur** [comment]
> @Proxcentaur The library APIs were changed sofar.
> 
> You need to provide the FirebaseJson object to the pushJSON function.
> 
> For example.
> 
> ```c++
> FirebaseJson json;
> 
> json.add("data1",100); //add (new) data
> json.set("data2/new", "test"); //set (replace or create new) the data
> 
> Firebase.pushJSON(firebaseData, "your_node_path", json);
> ```

thank you, it works!
