### ISSUE TITLE
ESP8266 Arduino Core SDK v3.x.x & MMU - Adjust the Ratio of ICACHE to IRAM

### ISSUE THREAD

**Issue by UltimatPronin** [mobizt/Firebase-ESP8266#200]
Hello! You wrote [You can stay with Core SDK v2.7.4 until this memory issue was solve in the Core SDK.]
Maybe this is not bug, but new configuration [feature](https://arduino-esp8266.readthedocs.io/en/3.0.0/mmu.html?highlight=heap) and we can use it?

**Comment by mobizt** [comment]
Thanks and I'll checking.

**Comment by mobizt** [comment]
It is the issue only in WiFiClientSecure and its memory allocation which  affected the free heap.
