### ISSUE TITLE
HELP Hostname for firebase

### ISSUE THREAD

**Issue by fionala-code** [mobizt/Firebase-ESP8266#203]
Hello, I'm trying to find the host name on my firebase project so i can add it in the initialization steps outlined in the Read.me file. However, I'm not exactly sure where I can find the host name. Some guidance would be appreciated!

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP8266#authentication

![Firebase Host](https://raw.githubusercontent.com/mobizt/Firebase-ESP8266/master/media/images/Firebase_Host.png)

**Comment by mobizt** [comment]
The FIREBASE_HOST is no more existed in all examples, It replaced by FIREBASE_URL
The FIRBASE_AUTH also replaced by DATABASE_SECRET

All new examples will uses Email/Password for authentication for more secure.

https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino
