### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by rendycahyae** [mobizt/Firebase-ESP8266#204]
Need help Sir, How do I get the amount of data on a path 
![Capture](https://user-images.githubusercontent.com/59685924/120002328-e9cc2280-bffe-11eb-810e-e519a60d18c7.PNG)

And I mean, I got the answer which is 3

**Comment by mobizt** [comment]
It's not possible to know the amount of data.

Firebase RTDB is not a normal cloud server that can compute but only storage with data query capability.

You can use Cloud Function for Firebase that can read and count data at the backend.
