### ISSUE TITLE
file timestamp.ino at example didnt work

### ISSUE THREAD

**Issue by Roni43-array** [mobizt/Firebase-ESP8266#213]
![Captu1re](https://user-images.githubusercontent.com/60907749/123620762-c3cfb300-d834-11eb-8180-7b28bc182b8b.JPG)

i've tried the example timestamp.ino and it appears like this. can u help me please

**Comment by mobizt** [comment]
It's about authentication issue.

Check your database rules and you need to provide the credentials(depends on your auth methods).

If you currently use the latest library version, the examples use email, password and private key, database url for authentication.

These credentials should be valid.  The email is the email of user in your project that you created or added it. The password is the password belongs to that email.

Read the document how to enable sign in provider in case you are not yet enable it.
