### ISSUE TITLE
WDT RESET every minute

### ISSUE THREAD

**Issue by Bingsitfx** [mobizt/Firebase-ESP8266#219]
Hello, I have a problem with the WDT reset (rst cause 4). this happens every minute. What should I do?
I transferred 11 data from arduino mega via serial communication line. Arduino will send data "xx#xx#" after getting data "xx*xx*" from nodemcu. Nodemcu sends the data at 2 second intervals.

This is my code
https://pastebin.com/3qmWvFNi

Im using ESP8266 board version 2.5.1
Firebase-ESP8266 version 3.0.7 
ArduinoJson version 5.13.1
Device : Nodemcu ESP8266-12F

**Comment by mobizt** [comment]
You post the wrong repository.

This is for FirebaseESP8266 library only.
