### ISSUE TITLE
Database secrets are currently deprecated

### ISSUE THREAD

**Issue by efitrillo** [mobizt/Firebase-ESP8266#224]
Greetings,
What can we do to deal with this when Google close the tap? Will this library be updated to use Firebase sdk? Its for a future proof project
https://i.stack.imgur.com/W9NpP.png
Thank you

**Comment by mobizt** [comment]
Did you have checked [these examples](https://github.com/mobizt/Firebase-ESP8266/tree/master/examples/Authentications)?

Or read the [document](https://github.com/mobizt/Firebase-ESP8266#authentication)?
