### ISSUE TITLE
HELP set bssl buffersize

### ISSUE THREAD

**Issue by ayyysh04** [mobizt/Firebase-ESP8266#226]
First of all library is super cool.
I want to know how can i set buffer size for big data as running below lines says there is no function like this.
Could u please tell the correct fnc name/example

CODE:
//Setting buffer for big data -
  firebaseData1.setBSSlBufferSize(1024,1024);
  firebaseData1.setResponseSize(1024);

**Comment by mobizt** [comment]
It's here
https://github.com/mobizt/Firebase-ESP8266/tree/master/src#firebase-data-object-functions

The problem is you choose incorrect board to compile, you need to select ESP8266 board.

**Comment by mobizt** [comment]
Typo in your code (l letter), should be **setBSSLBufferSize** instead of **setBSSlBufferSize**.

**Comment by ayyysh04** [comment]
Kk thanks it worked 😊
