### ISSUE TITLE
Reseting EPS8266 (EPS-01)

### ISSUE THREAD

**Issue by THSoftPoland** [mobizt/Firebase-ESP8266#230]
Please help with reseting my program using Firebase.setBool / Firebase.getBool (Firebase-ESP8266 ver 3.3.7)
This is (schematically) my program

[program.txt](https://github.com/mobizt/Firebase-ESP8266/files/6836245/program.txt)

and my Arduino board configuration

![esp8288config](https://user-images.githubusercontent.com/74735889/126067373-088afd3b-e4c6-4fed-a834-77694af71d0a.png)

Thank you
Tomasz

**Comment by mobizt** [comment]
improper usage with Firebase.begin
