### ISSUE TITLE
Configuring IP Address doesn't allow Firebase to begin properly

### ISSUE THREAD

**Issue by NiteAx** [mobizt/Firebase-ESP8266#231]
Hi, i'm having an issue where configuring a specific IP when starting Wifi causes firebase to never start.
```C++
      WiFi.mode(WIFI_STA);
      IPAddress local_ip(192, 168, 0, 100);
      IPAddress gateway(192, 168, 0, 1);
      IPAddress subnet(255, 255, 255, 0);
      //WiFi.config(local_ip, gateway, subnet);
      WiFi.begin(ssid, pass);
```
Firebase Client starts fine as long as the line of code is commented out in the snippet above. Otherwise, it just stops here:
![Firebase Client error](https://cdn.discordapp.com/attachments/350179664112779276/867609131996938280/unknown.png)

Is there a way around this?

**Comment by mobizt** [comment]
This is not a library issue.
Make sure your router provide the ip in range 192.168.0.x 
This question should ask on community forum e.g. stackoverflow or esp8266.com.
