### ISSUE TITLE
Blocking API

### ISSUE THREAD

**Issue by HamzaHajeir** [mobizt/Firebase-ESP8266#24]
Hello there

good work getting this library done.

There's hesitate about using this library, as its API are blocking for our code, which is damaging "multi-tasking". sometimes it takes 10 seconds to set an integer to DB!

I can't rely on it for that, Would you support it to be "async" library ?

Thanks

**Comment by mobizt** [comment]
Network delay or interruption depends on WiFi situation.
You can debug to find the root causes which async is not help in this case.

**Comment by mobizt** [comment]
MQTT may match your needs and async is not my in my plan but may be test and done it later.
