### ISSUE TITLE
StreamData's logic change

### ISSUE THREAD

**Issue by IliaSalaur** [mobizt/Firebase-ESP8266#248]
Hello, mobizt. Why did you change the StreamData's logics? In previous version StreamData.string Data() always returned data whenever if datatype wasnt String.  

I am asking this because this change ruined all my RTDB projects and I must rewrite all of them to fit the new logics

**Comment by mobizt** [comment]
You should explain with code. I don't understand what you mention.
The logic was not changed.

**Comment by mobizt** [comment]
I currently check and will fix it soon.

**Comment by mobizt** [comment]
The library was updated with this issue fixed. Sorry for the late update.
