### ISSUE TITLE
HELP NEEDED! stream + set/update under same node

### ISSUE THREAD

**Issue by ayyysh04** [mobizt/Firebase-ESP8266#249]
I wanted to ask that is this possible if we are streaming a node and wanted to update a node under it without knowing the stream?
if yes can you describe it how?

Thanks

**Comment by mobizt** [comment]
No

**Comment by mobizt** [comment]
The Google Firebase RTDB behavior. The stream event will be occurred as the value at stream path changes.

**Comment by ayyysh04** [comment]
ok thanks ,i got it
