### ISSUE TITLE
No device token provided on Firebase.sendTopic

### ISSUE THREAD

**Issue by arushgupta2007** [mobizt/Firebase-ESP8266#25]
Hi,

I am trying to use cloud messaging in esp8266 to give notification to android phone
My android phone has subscribed to the topic "general"

As a test I am sending the message in the **void setup** method

My esp8266 code :  

`

  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);

  Firebase.reconnectWiFi(true);

  firebaseData.fcm.begin("SECRET_KEY_IS_COPIED");

  firebaseData.fcm.setPriority("high");

  firebaseData.fcm.setTimeToLive(60);

  firebaseData.fcm.setNotifyMessage("Notification", "Hello World!", "firebase-logo.png", 
"http://www.google.com");
  firebaseData.fcm.setTopic("general");

  if (Firebase.sendTopic(firebaseData))
  {
    //Success, print the result returned from server
    Serial.println(firebaseData.fcm.getSendResult());
  }
  else
  {
    //Failed, print the error reason
    Serial.println(firebaseData.errorReason());
  }

`

And Error log:

`
No device token provided

`

Why do I need to give device token for topics?

**Comment by mobizt** [comment]
This is a bug and I jus fix this issue and update to v 2.1.2. 
Thank for your report.

**Comment by arushgupta2007** [comment]
Thanks

**Comment by arushgupta2007** [comment]
Is it updated? Can I re-download the library?

**Comment by mobizt** [comment]
Yes, you need to delete the old one and download new zip file from this GitHub. Arduino library manager was not the latest version.

**Comment by arushgupta2007** [comment]
Ok

**Comment by arushgupta2007** [comment]
It worked!
Thanks man, your library has saved my life 👍  :)

**Comment by afung2468** [comment]
Hi Mobizt. I am using Firebase ESP8266 Client Version 2.8.5. but I am still getting this "No device token provided" message. Which version should I use to get rid of this error? Thanks.

**Comment by mobizt** [comment]
@afung2468
The issue was fixed since v 2.1.2.

See the fcm [example](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Cloud_Messaging/Cloud_Messaging.ino)

**Comment by afung2468** [comment]
Thanks for the reply. I used the wrong function to send the topic. Your example does not show how to send a topic. After some experiments, it works now. Thank you.

**Comment by mobizt** [comment]
@afung2468

You need to read the doc rather than ask for everthing

https://github.com/mobizt/Firebase-ESP8266/tree/master/src#firebase-cloud-messaging-object-functions
