### ISSUE TITLE
Facing issue with multipath stream

### ISSUE THREAD

**Issue by Adityavj2699** [mobizt/Firebase-ESP8266#250]
I tried to run the example script. it compiled successfully and while running it doesn't execute the Streamcall back. I only have these logs can you please help me with this?
![Screenshot (379)](https://user-images.githubusercontent.com/39501029/131242407-31952432-af0f-4701-9315-da89b5355981.png)

**Comment by mobizt** [comment]
You should use discussions first.

You need to read the doc of the library for authentication.
https://github.com/mobizt/Firebase-ESP8266#authentication
