### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HoangPhuc3112** [mobizt/Firebase-ESP8266#255]
Hi !!!!!
Can someone help to get data in firebase ?
I can`t get data, I just receive "true" or "1" from Firebase

#include "DHT.h"
#include <ESP8266WiFi.h>
#include <FirebaseESP8266.h>
#include <ArduinoJson.h>
#define FIREBASE_HOST "https://test-b2337-default-rtdb.firebaseio.com/" //link DataBase
#define FIREBASE_AUTH "v56VrHG6NPsmteP0jOh9eOrSfyCogSEqhurS0jtn"
#define WIFI_SSID "kimchi123456"
#define WIFI_PASSWORD "123456789"
const int DHTPIN = D2;
const int DHTTYPE = DHT11;
DHT dht (DHTPIN, DHTTYPE);
FirebaseJson json;

FirebaseData getvalue ;
int x;
String path = "test-b2337-default-rtdb";

void setup() {
  dht.begin();
  Serial.begin(9600);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("connecting");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(50);
  }
  Serial.println();
  Serial.print("Contected: ");
  Serial.println(WiFi.localIP());
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  Firebase.reconnectWiFi(true);
}

void loop() {
  Serial.print("DatatBase: ");
  Firebase.getInt(getvalue , path "/data");
  delay(500);
}

**Comment by mobizt** [comment]
See [this example](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino) for how to use it properly.
