### ISSUE TITLE
BUG release 3.6.1 on github is shown as 3.6.2 in Arduino IDE

### ISSUE THREAD

**Issue by amitrao17** [mobizt/Firebase-ESP8266#275]
In the arduino IDE the library is shown as 3.6.2 but that release doesn't exist on github.

The 3.6.1 release on github has "3.6.2" in the source code...

Not a big deal but took me a minute to figure out what was going on.

Great library though!

**Comment by mobizt** [comment]
Thanks for report this issue, now it fixed.
