### ISSUE TITLE
Streaming stops after a while ..!

### ISSUE THREAD

**Issue by MrMakaVeLLi** [mobizt/Firebase-ESP8266#32]
Hi,
i'm using Firebase-ESP8266 Library, basically i'm using a mobile app to send and receive data from my firebase .
everything works fine but after several hours , streaming stops but i can send data ..!
so i can't receive a new data from the streaming path , so what is the problem ? 
thanks in advance .

**Comment by mobizt** [comment]
Read this issue https://github.com/mobizt/Firebase-ESP8266/issues/30

**Comment by MrMakaVeLLi** [comment]
i think my problem is very different 
my problem is that streaming stops without any condition and in random times !
it could be working for hours without problems and it could be work for only 2 minutes !

**Comment by MrMakaVeLLi** [comment]
> Read this issue #30

i think my problem is very different
my problem is that streaming stops without any condition and in random times !
it could be working for hours without problems and it could be work for only 2 minutes !

**Comment by mobizt** [comment]
Please debug WiFi and check the printed serial. Did you try #330 solution?. I didn't see your sketch, serial printed result and what's your WiFi type, I cannot tell anything.

**Comment by MrMakaVeLLi** [comment]
> Please debug WiFi and check the printed serial. Did you try #330 solution?. I didn't see your sketch, serial printed result and what's your WiFi type, I cannot tell anything.

that's the problem , when i debugging using serial when the streaming is lost, i got nothing !
no error message appeared like everything is running good !
here's my sketch for that part:
`if (WiFi.status() != WL_CONNECTED)
  {
    WiFi_Connect();
  }
  else
  {
    if (!Firebase.readStream(firebaseData))
    {
      Serial.println("Can't read stream data");
      Serial.println("REASON: " + firebaseData.errorReason());
      Serial.println();
    }
    if (firebaseData.streamTimeout())
    {
      Serial.println("Stream timeout, resume streaming...");
      Serial.println();
    }
    if ( !Firebase.beginStream(firebaseData, path + "/State") )
    {
      Serial.println("Can't read stream data");
      Serial.println("REASON: " + firebaseData.errorReason());
      Serial.println();
      ESP.restart();
    }
    if (firebaseData.streamAvailable())
    {
      val = firebaseData.stringData().toInt();
    }`

**Comment by mobizt** [comment]
This part is not need, the library will check the internet connection and report the ploblem for you.

```C++
if (WiFi.status() != WL_CONNECTED)
{
    WiFi_Connect();
}

```

**Comment by MrMakaVeLLi** [comment]
> This part is not need, the library will check the internet connection and report the ploblem for you.
> 
> ```c++
> if (WiFi.status() != WL_CONNECTED)
> {
>     WiFi_Connect();
> }
> ```

so , that's what causing the problem ?!

**Comment by mobizt** [comment]
Where is this part of your code at, setup or loop?

**Comment by MrMakaVeLLi** [comment]
> Where is this part of your code at, setup or loop?

both ,
void WiFi_Connect()
{
 while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
  }
  Serial.println("Connected !");
}
void setup()
{
  Serial.begin(115200);
  pinMode(latchPin, OUTPUT);
  pinMode(dataPin, OUTPUT);
  pinMode(clockPin, OUTPUT);
  EEPROM.begin(512);
  wifi_set_sleep_type(NONE_SLEEP_T);
  delay(100);
  for ( int i = 1; i <= 16; i++ )
  {
    Turn(i, EEPROM.read(i));
  }
  WiFi_Connect();
  Serial.println();
  Serial.println(WiFi.localIP());
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  Firebase.reconnectWiFi(true);
  if (!Firebase.beginStream(firebaseData, path + "/State"))
  {
    Serial.println("------------------------------------");
    Serial.println("Can't begin stream connection...");
    Serial.println("REASON: " + firebaseData.errorReason());
    Serial.println("------------------------------------");
    Serial.println();
  }
  else
  {
    Serial.println("PASSED");
    Serial.println("------------------------------------");
    Serial.println();
  }
}

**Comment by MrMakaVeLLi** [comment]
> Where is this part of your code at, setup or loop?

both

void WiFi_Connect()
{
 while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
  }
  Serial.println("Connected !");
  Serial.println();
  Serial.println(WiFi.localIP());
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
  Firebase.reconnectWiFi(true);
}
void setup()
{
  Serial.begin(115200);
  pinMode(latchPin, OUTPUT);
  pinMode(dataPin, OUTPUT);
  pinMode(clockPin, OUTPUT);
  EEPROM.begin(512);
  wifi_set_sleep_type(NONE_SLEEP_T);
  delay(100);
  for ( int i = 1; i <= 16; i++ )
  {
    Turn(i, EEPROM.read(i));
  }
  WiFi_Connect();
  if (!Firebase.beginStream(firebaseData, path + "/State"))
  {
    Serial.println("------------------------------------");
    Serial.println("Can't begin stream connection...");
    Serial.println("REASON: " + firebaseData.errorReason());
    Serial.println("------------------------------------");
    Serial.println();
  }
  else
  {
    Serial.println("PASSED");
    Serial.println("------------------------------------");
    Serial.println();
  }
}

**Comment by mobizt** [comment]
**Firebase.readStream** must be in loop and try to avoid to use blocking code (time consumed work) or delay in that loop.

**Firebase.beginStream** must be call once in setup and should not call it again for the same streaming path. 

If you use the same Firebase Data object to normal firebase calls and stream. This will interrupts stream connection and you not need to call **beginStream** again to reume, it resumed automatically with **Firebase.readStream** as long as r**eadStream** runs in the loop.

If you want to stream multiple streaming path using **Firebase.beginStream**  somewhare in your loop, it's not efficient because it breaks your last streaming and reconnect to new streaming with difference streaming paths.

**Comment by MrMakaVeLLi** [comment]
i will try to delete **Firebase.beginStream** in the loop and try again
i'm using only one streaming object , i used Firebase.pushInt() function only for testing the connectivity to firebase and the result was firebase is still connected and i can send but i can't receive ( after problem happened )

**Comment by mobizt** [comment]
Keep **Firebase.readStream** in loop, it will check the Firebase connection for you without to test by set any value to Firebase and if you use the same Firebase Data object, call any Firebase function (get/set/push/update/delete) will break the stream and resumed automatically.

**Comment by MrMakaVeLLi** [comment]
thanks a lot, problem is fixed after removing 
**if ( !Firebase.beginStream(firebaseData, path + "/State") )**
from the loop .
if wifi is dropped , the default of the library is reconnecting ?

**Comment by mobizt** [comment]
Yes, if you callFirebase.reconnectWiFi(true) once in set up.

**Comment by asifakhtar98** [comment]
Firebase Firestore Stream Subscription automatically stopping in Flutter Apps. I have got this issue with all state managements packages. I think this problem in Firebase itself, not in client apps.

**Comment by amy1school** [comment]
Streaming stop after a while, I tried in multiple ways but did not worked.  Please help me 


const int led = LED_BUILTIN;
const int led2 = 4;   //d2
const int led3 = 14;  //d6

#include <EEPROM.h>
#include <FirebaseESP8266.h>
#include "addons/TokenHelper.h"
#include "addons/RTDBHelper.h"

#include <WebSocketsServer.h>
#include <ESP8266WiFiMulti.h>
#include <ArduinoJson.h>
ESP8266WiFiMulti wifiMulti;
WebSocketsServer websockets(81);
const uint32_t connectTimeoutMs = 5000;

String esid; 
String epass = "";
String temp_path;
String temp_value;
String temp_code;

String fbdo_err ="";

#define USER_EMAIL "  "
#define USER_PASSWORD "  "

#define API_KEY "    "
#define DATABASE_URL "   "

FirebaseData fbdo;
FirebaseAuth auth;
FirebaseConfig config;

String uid;
String databasePath;
String fbdoPath;

unsigned long fb_uid_new_millis=0;
unsigned long fb_uid_old_millis=0;
unsigned long fb_uid_wait =5000;

unsigned long internet_new_millis=0;
unsigned long internet_old_millis=0;
unsigned long internet_wait=5000;

//unsigned long wifi_new_millis=0;
unsigned long wifi_old_millis=0;
const long wifi_wait=15000;

unsigned long i_new_millis=0;
unsigned long i_old_millis=0;
unsigned long i_wait =12000;

int b=0;
int c=0;
int internet=0;
int internet2=0;
int fb=0;
int tb=0;
int ws_s=0;
int j=0;
int k=0;
int Timeout=2;
int feed=0;
String feed_v="";
String path_i="";
String value_i="";

void wifi_update(void);
void fireBase_setup(void); 
void offline_server(void);
void output();

void writeString(char add,String data); // EEPROM
String read_String(char add);

void sendFloat(String path, String feed_v)   
{
  Firebase.RTDB.setString(&fbdo, path.c_str(), feed_v);
} 

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) // WS EVENT
{
  DynamicJsonDocument doc(200);
  switch (type) 
  {
    case WStype_DISCONNECTED:
        ws_s=2;
        delay(550);
       break;
      
    case WStype_CONNECTED: 
      {
        IPAddress ip = websockets.remoteIP(num);
        ws_s=1;
        delay(550);
      }
      break;
      
    case WStype_TEXT:
      String message = String((char*)(payload));
         
      DeserializationError error = deserializeJson(doc, message);
      if (error) 
      {
        Serial.print("deserializeJson() failed: ");
        Serial.println(error.c_str());
        return;
      }

    String ws_path  = doc["path"];
    String ws_value = doc["value"];
           
    String null;
    if(ws_value !=null)
    { 
      serializeJson(doc, Serial);
      if(ws_path=="u_ssid: ")
      {
        writeString(10, ws_value);
        Serial.print("EEPROM Writing SSID: ");
        Serial.println(ws_value);
      }
      else if(ws_path=="u_pass: ")
      {
        writeString(30, ws_value);
        Serial.print("EEPROM Writing PASS: ");
        Serial.println(ws_value);
        delay(50);
        ESP.restart();
      }  
     }
   }
}


void setup() 
{
  Serial.begin(115200); 
  EEPROM.begin(128);
  pinMode(led, OUTPUT);
  digitalWrite(led, HIGH);
  pinMode(led2, OUTPUT);
  digitalWrite(led2, LOW);
  pinMode(led3, OUTPUT);
  digitalWrite(led3, LOW);
  delay(1000);
  Serial.println();                    /////////////
  StaticJsonDocument<300> doc;
  doc["wifi"]="Connecting...";
  doc["ip"]="Connecting...";
  doc["ws"]="Starting...";
  doc["fb"]="Resuming";
  doc["path"]="...";
  doc["value"]="...";
  serializeJson(doc, Serial);
  esid = read_String(10);
  epass = read_String(30);
  delay(500);
  Serial.println();
  Serial.print("esid: ");
  Serial.println(esid);
  Serial.print("PASS: ");
  Serial.println(epass);
  wifi_update(); 
}

void loop() 
{ 
 websockets.loop();
 Firebase.readStream(fbdo);
 if (fbdo.streamAvailable())
 {
   handlePin(fbdo.dataPath(), fbdo.stringData());
 }

 if(ws_s!=0)
 {
   Serial.println();                            /////////////////////////////////
   delay(550);
   DynamicJsonDocument doc(20);
   if(ws_s==1){doc["ws"]="Connected";}
   else{doc["ws"]="Disconnected";}
   serializeJson(doc, Serial);
   ws_s=0;
 } 
 if(feed==1)
 {
   Serial.println("restart");
   feed=0;
   String feedPath = "/UsersData/" + uid + "/feed2";
   sendFloat(feedPath, feed_v);
   delay(500);
   ESP.restart();
 }
}

void offline_server(void)
{
  websockets.begin();
  websockets.onEvent(webSocketEvent);
}

void fireBase_setup(void)
{
  config.api_key = API_KEY;
  auth.user.email = USER_EMAIL;
  auth.user.password = USER_PASSWORD;
  config.database_url = DATABASE_URL;

  Firebase.reconnectWiFi(true);
  Firebase.setMaxRetry(fbdo, 3);
  fbdo.setBSSLBufferSize(1024, 1024);
  fbdo.setResponseSize(4096);

  config.token_status_callback = tokenStatusCallback; //see addons/TokenHelper.h
  Firebase.begin(&config, &auth);

  Serial.println("Getting User UID");
  fb_uid_new_millis= millis();
  while (fb_uid_new_millis - fb_uid_old_millis >= fb_uid_wait && (auth.token.uid) == "") 
  {
    fb_uid_old_millis= fb_uid_new_millis;
  }
  
  uid= auth.token.uid.c_str();
  DynamicJsonDocument doc(200);
  doc["UID"]=uid;
  serializeJson(doc, Serial);
  databasePath = "/UsersData/" + uid;
  Firebase.beginStream(fbdo, databasePath);

  if(!Firebase.beginStream(fbdo, databasePath))
  {
    DynamicJsonDocument doc(200);
    doc["fb"]= fbdo.errorReason();
    serializeJson(doc, Serial);  
  }
  if(Firebase.ready())
  {
    DynamicJsonDocument doc(200);
    doc["fb"]="Available";
    serializeJson(doc, Serial);
  }
}

void handlePin(String path, String value)
{
  Serial.println();                            ////////////////////////////////////
  DynamicJsonDocument doc(200);
  doc["path"] = path;
  doc["value"] = value;
  serializeJson(doc, Serial);
  path_i=path;
  value_i=value;
  output();
}


void wifi_update(void)
{
  WiFi.mode(WIFI_STA);
  wifiMulti.addAP("      " , "       ");  
  wifiMulti.addAP(esid.c_str(),epass.c_str());
  if (wifiMulti.run(connectTimeoutMs) == WL_CONNECTED) 
  {
    k=1;
    Serial.println();                                     //////////////////////
    DynamicJsonDocument doc(200);
    doc["ws"] = "Started";                    
    doc["ip"] = WiFi.localIP(); 
    doc["wifi"] = WiFi.SSID(); 
    serializeJson(doc, Serial);
    fireBase_setup();
    offline_server(); 
  }
  else 
  {
    k=0;
    Serial.println();                                   //////////////////////////////////////
    DynamicJsonDocument doc(200);
    doc["wifi"] = "Connection Err";
    doc["ws"] = "Unavailable";                    
    doc["ip"] = "Unavailable"; 
    doc["fb"] ="Unavailable"; 
    doc["path"]="...";
    doc["value"]="...";
    serializeJson(doc, Serial);
  }
}


void writeString(char add,String data)
{
  int _size = data.length();
  int i;
  for(i=0;i<_size;i++)
  {
    EEPROM.write(add+i,data[i]);
  }
  EEPROM.write(add+_size,'\0'); 
  EEPROM.commit();
}

String read_String(char add)
{
  int i;
  char data[100]; //Max 100 Bytes
  int len=0;
  unsigned char k;
  k=EEPROM.read(add);
  while(k != '\0' && len<500)   
  {    
    k=EEPROM.read(add+len);
    data[len]=k;
    len++;
  }
  data[len]='\0';
  return String(data);
}


void output()
{
  if(path_i == "/hl1")
  {
      if(value_i == "1")
      {
        digitalWrite(led3, HIGH);
      }
      else
      {
         digitalWrite(led3, LOW);  
      }  
  }
  if(path_i == "/feed")
  {
    feed=1;
    feed_v=value_i;
    delay(500);
  }  
}

**Comment by mobizt** [comment]
@amy1school 

Check the examples and read all comments in the examples to use the library properly, what you should do and don't.
