### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by AravindhSivakumar98** [mobizt/Firebase-ESP8266#321]
firebase_test.ino: In function 'void printResult(FirebaseData&)':
firebase_test:134:28: error: 'JSON_OBJECT' was not declared in this scope
       Serial.print(type == JSON_OBJECT ? "object" : "array");
                            ^
firebase_test:166:31: error: 'JSON_BOOL' was not declared in this scope
       if (jsonData.typeNum == JSON_BOOL)
                               ^
firebase_test:168:36: error: 'JSON_INT' was not declared in this scope
       else if (jsonData.typeNum == JSON_INT)
                                    ^
firebase_test:170:36: error: 'JSON_DOUBLE' was not declared in this scope
       else if (jsonData.typeNum == JSON_DOUBLE)
                                    ^
firebase_test:172:36: error: 'JSON_STRING' was not declared in this scope
       else if (jsonData.typeNum == JSON_STRING ||
                                    ^
firebase_test:173:36: error: 'JSON_NULL' was not declared in this scope
                jsonData.typeNum == JSON_NULL ||
                                    ^
firebase_test:174:36: error: 'JSON_OBJECT' was not declared in this scope
                jsonData.typeNum == JSON_OBJECT ||
                                    ^
firebase_test:175:36: error: 'JSON_ARRAY' was not declared in this scope
                jsonData.typeNum == JSON_ARRAY)

**Comment by mobizt** [comment]
You are using the old code for the new library which is not compatible.

If you updated the library, follow the examples based on the library version you used.

With the current released, see [here](https://github.com/mobizt/Firebase-ESP8266/blob/master/src/addons/RTDBHelper.h) for the information printing
