### ISSUE TITLE
Firestore reads are continuous! Want to read only when there is a change in firestore database

### ISSUE THREAD

**Issue by jbl584** [mobizt/Firebase-ESP8266#324]
The issue was that this library keeps on reading the values from firestore or if we set the time interval of read.
It leads to crossing the read values and write values allowed on firestore wherein it leads to quota exceeded.

I want to know if there's an option of reading the value only if there's a change in data in firestore and then it reads. This way the read values wont cross the quota.

**Comment by mobizt** [comment]
Wrong repository
