### ISSUE TITLE
Firestore values are conitnuously reading. I want to read only when it changes in firestore 

### ISSUE THREAD

**Issue by jbl584** [mobizt/Firebase-ESP8266#325]
I'm using ESP8266 and Firestore GetDocument example. I get values from firestore and turn on relay.

The issue was that this library keeps on reading the values from firestore or if we set the time interval of read.
It leads to crossing the read values and write values allowed on firestore wherein it leads to quota exceeded.

I want to know if there's an option of reading the value only if there's a change in data in firestore and then it reads. This way the read values wont cross the quota.

What is wrong repository?

**Comment by mobizt** [comment]
What place to post.

Check the library you use and go to the library repo.
