### ISSUE TITLE
esp8266 firestore changes

### ISSUE THREAD

**Issue by ganeshchinimilli** [mobizt/Firebase-ESP8266#326]
Hai everyone,just need favour.

We implemented reading data from firestore using esp8266.But what it does is it continuously fetches data from firestore .
so the daly for remaining operations increases.Can i get a clue in which way i fetch data from firestore only when the data changes in the database.

Thanks in advance

**Comment by mobizt** [comment]
If you mean Firestore and use Firebase-ESP-Client library, this stream like operation or realtime data changes listening is not available from the REST API that this library works for.

Alternatively you can use Cloud Functions for Firebase to listen the data changes in Firestore document and send acknowledge for the changes to other system e.g. set or change the data that is streaming in RTDB then you can get notified from RTDB stream or calling the web hook to some server when Firestore document changed.
