### ISSUE TITLE
BUG id token (GITKit token), status = error

### ISSUE THREAD

**Issue by khanfar** [mobizt/Firebase-ESP8266#353]
after upload sketch , in monitor i see these error please help : 
Token error: code: 400, message: bad request
Token info: type = id token (GITKit token), status = on request
Token info: type = id token (GITKit token), status = error
Token error: code: 400, message: CONFIGURATION_NOT_FOUND
Token info: type = id token (GITKit token), status = error
Token error: code: 400, message: bad request
Token info: type = id token (GITKit token), status = on request
Token info: type = id token (GITKit token), status = error
Token error: code: 400, message: CONFIGURATION_NOT_FOUND

**Comment by mobizt** [comment]
Remove all Firebase libraries found in Arduino libraries folder and install the latest version from Library Manager.

**Comment by khanfar** [comment]
What's library name to install from manager ?

**Comment by mobizt** [comment]
[Firebase ESP8266 Client](https://www.arduinolibraries.info/libraries/firebase-esp8266-client)
