### ISSUE TITLE
I'm trying to read this data

### ISSUE THREAD

**Issue by Pratamatanar** [mobizt/Firebase-ESP8266#359]
how do i read all values ​​from this data:
```
{
  "alarm": {
    "-NQF0Wy4BqMRi-8Twr8y": "14:16",
    "-NQF0i1yEN3g3mqLCUOO": "02:16",
    "-NQF0kbTvQcDEqFQbz6X": "02:16",
    "-NQF0nSiEXBn9weXgnKR": "19:09",
    "-NQP5ONwpNvqrKmXVyE8": "15:13"
  }}
```
using the `for loop` technique

**Comment by mobizt** [comment]
How can you parse it without using library e.g., searching for "" and get string from it? If not, it's not possible.

**Comment by mobizt** [comment]
Please use [discussions](https://github.com/mobizt/Firebase-ESP8266/discussions) for asking question instead.
