### ISSUE TITLE
FirebaseDataObject.clear() is not working

### ISSUE THREAD

**Issue by 0111101010110** [mobizt/Firebase-ESP8266#363]
Currently, I am using Firebase ESP Client version 4.3.9. 

This is my code:
#include <Firebase_ESP_Client.h>

FirebaseData FirebaseDataObject;

void do_a_func()
{
	if(do something successfully)
	{
		FirebaseDataObject.setBSSLBufferSize(2048 /* Rx buffer size in bytes from 512 - 16384 */, 2048 /* Tx buffer size in bytes from 512 - 16384 */);
		FirebaseDataObject.setResponseSize(2048);
	}
	else
	{
		// Do other thing
	}
}

void setup()
{
	// do something here
	do_a_func();
}

void loop()
{

	FirebaseJson SensorDataContent;
	
	// Task 1
	SensorDataContent.set("fields/timestamp/timestampValue", safe_str_timestamp.c_str());
	FirebaseDataObject.pauseFirebase(false);
	if (Firebase.ready()) 
	{
		if(&FirebaseDataObject, Firebase_project_name, "", "fixed/document/path", SensorDataContent.raw())) 
		{
		  Serial.println("Task 1 success.");
		}

		else 
		{
		  Serial.println(FirebaseDataObject.errorReason());
		}
	}
	FirebaseDataObject.pauseFirebase(true);
        FirebaseDataObject.clear();

	// Task 2
	SensorDataContent.clear()
	SensorDataContent.set("fields/string/stringValue", "random string");
	FirebaseDataObject.pauseFirebase(false);
	if (Firebase.ready()) 
	{
		if(&FirebaseDataObject, Firebase_project_name, "", "random/document/path", SensorDataContent.raw())) 
		{
		  Serial.println("Task 2 success.");
		}

		else 
		{
		  Serial.println(FirebaseDataObject.errorReason());
		}
	}
	FirebaseDataObject.pauseFirebase(true);
        FirebaseDataObject.clear();
	
	
	
	// Task 3
	FirebaseDataObject.pauseFirebase(false);
	if(Firebase.ready())
	{
		if (Firebase.Firestore.deleteDocument(&FirebaseDataObject, Firebase_project_name, "", "random/document/path"))
		{
		  Serial.println(" Task 3 success.");
		}
		else
		{
		  Serial.println(FirebaseDataObject.errorReason());
		}
	}
	FirebaseDataObject.pauseFirebase(true);
        FirebaseDataObject.clear();
}

The output I get is:
Task 1 success
Task 2 success
Task 3 success

Then: 
Document already exists: projects/testFirebase/databases/(default)/documents/fixed/document/path
Task 2 success
Task 3 success

After 3 ~ 8 hours:
Document already exists: projects/testFirebase/databases/(default)/documents/fixed/document/path
Document already exists: projects/testFirebase/databases/(default)/documents/fixed/document/path
Document already exists: projects/testFirebase/databases/(default)/documents/fixed/document/path

It cause my task 2 and 3 fail. Why?

**Comment by mobizt** [comment]
You are misunderstanding in the clear function. It used for library internal usage memory releasing.

**Comment by 0111101010110** [comment]
I am very new to the NodeMCU, so is there any method to overcome this?

**Comment by mobizt** [comment]
You have the problem with your programming logic.

This line is not complete or you are accidentally erased something before posting.

`if(&FirebaseDataObject`, 

But with the error returns from server indicates that you are trying to create the document that is already existed.

**Comment by 0111101010110** [comment]
Noted. I will fix and try again.
