### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by ledainghia** [mobizt/Firebase-ESP8266#367]
Dear ,

I hope this email finds you well. I am writing to you regarding an issue I encountered while using the FirebaseESP8266 library, which seems to conflict with the WiFiClientSecure library, preventing the client from establishing a connection with the desired host.

Description of the issue:

When attempting to connect to a host using WiFiClientSecure, the connection fails, and I am unable to establish a connection to the intended host.
This issue arises after including both the FirebaseESP8266 and WiFiClientSecure libraries in my program.
I have verified that the issue is not related to the network or the host since I was able to establish a successful connection when not using the FirebaseESP8266 library.
Steps to reproduce the issue:

Include the WiFiClientSecure and FirebaseESP8266 libraries in the program.
Set up the WiFiClientSecure connection and attempt to connect to a host.
Result: The connection fails, and I am unable to establish a connection to the host.
I have tried some solutions, such as updating both the FirebaseESP8266 and WiFiClientSecure libraries to the latest version, but the issue still persists.

I am in urgent need of your assistance to resolve this matter. I kindly request you to review and provide a solution or bug fix for this issue.

Thank you for your time and effort in developing the FirebaseESP8266 library. I look forward to your prompt response.

**Comment by mobizt** [comment]
There is nothing related to the library.

The important when you are working with WiFiClientSecure (using BearSSL SSL library engine) is memory consumption.

You should debug your code for WiFi, SSL and OOM via Arduino IDE debug options, and check your device free heap as WiFiClientSecure object requires maximum 16k memory by default.

You can set the amount of reserve memory for in and out buffers of WiFiClientSecure's BearSSL engine from 512 bytes to 16384 bytes by calling `setBufferSizes` (search google for how to do this).  

Your SSL client will be unable to connect to server in case of memory allocation failure as your device free heap is not enough which causes TLS handshake failure.

Please make sure you read and set the heap amount of your device correctly from [this doc](https://github.com/mobizt/Firebase-ESP8266#memory-options-for-esp8266).

This library also creates the WiFiClientSecure instant inside the FirebaseData object to work with Firebase server.

**Comment by mobizt** [comment]
You will see the library implemented this BearSSL memory reserved options for internal WiFiClientSecure used in the `FirebaseData` object [here](https://github.com/mobizt/Firebase-ESP8266/blob/95613ddab1c39aaf246bfddf302c953dd24cbdd7/examples/File/Flash/Flash.ino#L121).

**Comment by ledainghia** [comment]
I tried setting the heap amount of your device as your doc gave but it
seems to run. My board Wemos d1r2(EPS8266) hangs and restarts by itself. It
can't solve the problem I'm having

*I*


Vào Th 2, 29 thg 5, 2023 vào lúc 15:34 Suwatchai K. <
***@***.***> đã viết:
