### ISSUE TITLE
getInt ve setInt

### ISSUE THREAD

**Issue by mesut25** [mobizt/Firebase-ESP8266#38]
Firebase.setInt("mes",0); 
r=Firebase.getString("mes").toInt();

what are the exact equivalents of these codes.
your samples are very difficult.
your samples are very complex.

**Comment by mobizt** [comment]
That  functions are not mine. 

Make sure you are not confused between my Firebase library and others.

Many examples available, this is [one you should follow](https://github.com/mobizt/Firebase-ESP8266/tree/master/examples/Basic)
