### ISSUE TITLE
BUG Token info: type = id token (GITKit token), status = on request

### ISSUE THREAD

**Issue by ThongNguyen182003** [mobizt/Firebase-ESP8266#381]
void setUpFirebase(){
  config.api_key = API_KEY;
  config.database_url = DATABSE_URL;
  /*Sign Up*/
  if(Firebase.signUp(&config, &auth, "", "")){
    Serial.println("Sign up Firebase OK !!!");
    signUp = true;
  } else{
    Serial.printf("%s\n", config.signer.signupError.message.c_str());
  }
  /*-- Call Back --*/
  config.token_status_callback= tokenStatusCallback;

  Firebase.begin(&config, &auth);
  Firebase.reconnectWiFi(true);
}
void setup() {
  pinMode(BUILTIN_LED, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(115200);
  dht.begin();
  setup_wifi();
  setUpFirebase();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

/* ------ EROROR ----------- */ 
Connecting to thong
..............
WiFi connected
IP address: 
192.168.219.14

Token info: type = id token (GITKit token), status = on request
Token info: type = id token (GITKit token), status = error
Token error: code: 408, message: request timed out
Token info: type = id token (GITKit token), status = on request
/*------------- Version ----------------*/
mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.8

**Comment by mobizt** [comment]
This is the internet access problem, please check it.
