### ISSUE TITLE
I've been getting a connection refused after a few seconds after connection to firebase

### ISSUE THREAD

**Issue by MokaChaos** [mobizt/Firebase-ESP8266#386]
So i've been working on a project doing IoT based IR transmitter using ESP32 C3 Super Mini with a couple of Firebase.getInt and Firebase.setInt in a 1000 ms interval.

though since my code doesn't work and keep getting the connection refused error, i've decided to try the example "basic" from the firebase ESP32 client library and try to recreate the error.

![image_2023-12-07_092255975](https://github.com/mobizt/Firebase-ESP8266/assets/121289042/13908ac0-2a43-4d32-abb4-2a38e249f4d6)

i've tried the original "basic" code and let it run for a while, and it turns out fine even up until 500+ repetitions. then after that I tried changing the millis delay to 1000ms instead of 15000ms the original code has. it runs up until like 15 repetition and then gave the "connection refused" error. so i wonder if there's some kind of specific minimal delay the library can handle that makes the rapid change doesn't work?

![image_2023-12-07_092146508](https://github.com/mobizt/Firebase-ESP8266/assets/121289042/e6695bee-ac04-4885-af4d-ebb38eb673f2)

if you need me to provide more details or try something regarding the issue, i'd be happy to provide it. Thanks

**Comment by mobizt** [comment]
This is the repo for ESP8266.

It is because the data bandwidth quota limit or network issue.

If you want to get the instant data update, use stream instead.
https://github.com/mobizt/Firebase-ESP8266/tree/master/examples/DataChangesListener
