### ISSUE TITLE
BUG FirebaseESP8266.h with version @^4.4.12 of Library

### ISSUE THREAD

**Issue by Marek128b** [mobizt/Firebase-ESP8266#391]
**Describe the bug**
the function dose not work with esp8266 as the FirebaseESP8266.h file does not exist. error in addon RTDBHelper.h

`#elif defined(ESP8266) || defined(MB_ARDUINO_PICO)
#include <FirebaseESP8266.h>
#endif`

**To Reproduce**
1. have a ESP8266 `d1_mini_lite`
1. include `#include <addons/RTDBHelper.h>`
2. See error

**Expected behavior**
no problems to import RTDBHelper.h

**Screenshots**
in Main.cpp
![image](https://github.com/mobizt/Firebase-ESP8266/assets/58476072/fa1bb88b-11eb-4aff-8151-67f6e3a46918)

in addons/RTDBHelper.h
![image](https://github.com/mobizt/Firebase-ESP8266/assets/58476072/38d1d5f7-265a-471a-8c34-e6b0e35f2705)

in PlatfomIO.ini
![image](https://github.com/mobizt/Firebase-ESP8266/assets/58476072/155db516-fa1c-40da-bbd1-8ccce19255eb)

**IDE and its version:**
 - PlatformIO
 - Version [6.1.13]

**Additional context**
nothing more

**Comment by mobizt** [comment]
Error is on your side instead and library works normally.

**Comment by mobizt** [comment]
Check your library installation.
https://github.com/mobizt/Firebase-ESP8266/blob/master/src/FirebaseESP8266.h

Don't install library on network drive e.g. OneDrive.

**Comment by mobizt** [comment]
For PIO, you have to clean the project when you edit the platformio.ini.

**Comment by mobizt** [comment]
FYI.

All my libraries developed in PlatformIO and test for both PlatformIO and Arduino.
