### ISSUE TITLE
Content Available for FCM_HTTPv1_JSON_Message

### ISSUE THREAD

**Issue by EmbeddedAyoub** [mobizt/Firebase-ESP8266#394]
Hello,

Thanks for this amazing Library which helped me a lot!

I am wondering how I can send "content-available" value in a http/jason format using this struct FCM_HTTPv1_JSON_Message.

I know it was already present in FCM_Legacy_HTTP_Message but not anymore in FCM_HTTPv1_JSON_Message.

I wanna send it like this:
{
    "ttl":"10s",
   "to": "dQkY26Skck3otuazbr57Kc:APA91bEX5yd8l1j9FF5vxVPaApxzblKkUamd8E0gNUYY41gdOLBBteApCEZtV5W-lZF4eNTmaJ546Ffy6ZhDWkY_-cCpFkBlZKCUJCtBp34yzAk4_7jLYTZXHVVs72JybSVkQ8ADUhC0",
   "content_available": true,
   "data":
   {
      "message": "Fuite de Gaz"
   },
   "notification":
   {
      "body": "Fuite de gaz",
      "sound": "default"
   },
    "apns": {
       "headers": {
         "apns-priority": "10"
       },
       "payload": {
         "aps": {
           "category": "NEW_MESSAGE_CATEGORY"
         }
       }
     }
}

Do you have any idea how I can send it?

Thanks,
Ayoub

**Comment by mobizt** [comment]
As stated in Readme, please use new [FirebaseClient](https://github.com/mobizt/FirebaseClient) library instead.
