### ISSUE TITLE
Support for unsigned integer in JSON Object

### ISSUE THREAD

**Issue by Touqeer-Hussain** [mobizt/Firebase-ESP8266#60]
Currently JSON Object doesn't support unsigned integer!!

**Comment by mobizt** [comment]
How about your use case to use that large number?

**Comment by Touqeer-Hussain** [comment]
I was adding Timestamp into JSON Object which is 16 digits but setTimestemp return 10 digit timestemp which i understood later that it can be multiplied by 1000 to get correct time so the issue is resolved.
