### ISSUE TITLE
A little mistake in desciption (Read Data)

### ISSUE THREAD

**Issue by komputerboy** [mobizt/Firebase-ESP8266#67]
I've a little mistake in your exmaple program at the description (Read Data):

```
 if (Firebase.getInt(firebaseData, "/test/int")) {

    if (firebaseData.dataType() == "int")) {
      Serial.println(firebaseData.intData());
    }

  } else {
    Serial.println(firebaseData.errorReason());
  }
```

in here:
` if (firebaseData.dataType() == "int")) {`

i think it should be

` if (firebaseData.dataType() == "int") {`

**Comment by mobizt** [comment]
Thanks.
I will correct it

**Comment by komputerboy** [comment]
okay
