### ISSUE TITLE
Is it possible to Update a node without triggering the stream?

### ISSUE THREAD

**Issue by majorlennox** [mobizt/Firebase-ESP8266#73]
I know, that this might have been covered already but I can't find it so I'll just ask.
I have the ESP8266 streaming a node in my real time database. Can I change the value of that node without triggering the Stream?
Thanks in advance.

**Comment by mobizt** [comment]
Any child node value changes/updates will be trigged the stream event of parent node that being stream. This is Firebase RTDB behavior.
