### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by amansinghaljpr** [mobizt/Firebase-ESP8266#77]
I tried the basic example and i am getting : 

FAILED
REASON: read Timeout
------------------------------------

In every test , i dont understand why that's happening

**Comment by mobizt** [comment]
Check that your esp8266 is actually connect to internet (not only WiFi connected).

Your router may not response any data to device, reset router or change router or use mobile/PC WiFi hotspot.

Test internet connectivity by making simple http request (see in Arduino example) or ping by using ping library.

**Comment by amansinghaljpr** [comment]
The problem is that the data is getting updated on the firebase , the serial monitor shows the error so its a proof that the data is getting uploaded its just that something or somewhere else is the problem

**Comment by mobizt** [comment]
Nothing update in your database,as no response from firebase server due to no internet connection issue.

Did you try my suggestion above?

**Comment by mobizt** [comment]
Use your mobile phone to share WiFi hotspot to esp8266.

**Comment by amansinghaljpr** [comment]
Yes i did tried your suggestion and the firebase is right in front of me , the data is getting updated but there is no response on the serial monitor .

**Comment by mobizt** [comment]
Update esp8266 package (Arduino Core SDK) from board managers to latest version. 

Share your code here.

**Comment by mobizt** [comment]
How about making http request and ping test?  Share your test code (ping or http request) and result.

**Comment by amansinghaljpr** [comment]
Okay so i did some research and i found the problem. The problem is not with the code but the type of board which i was using  Although the on i have is very similar to nodemcu but its actually not . Maybe the firmware of that chip was making it incompatible.
Also i would recommend you to put this in your repository that this library wont work properly on this particular
![images (2)](https://user-images.githubusercontent.com/9629504/72249298-14425900-361f-11ea-9fd1-11f5d8ac5227.png)

 board . 

This is the image of the board:
![images (2)](https://user-images.githubusercontent.com/9629504/72249343-2fad6400-361f-11ea-9d25-eac34a452b43.png)

**Comment by mobizt** [comment]
The board you showed  from robotdyn uses Espressif ESP8266EX mcu as in Node MCU and Wemos D1 Mini. 

It has 4 MB (32 Mbit flash) as in other boards and nothing is special.

In Arduino IDE, you can choose board Wemos D1 mini or Generic ESP8266 and choose proper flash size and SPIFFS for this board.

If you still get the error, the board you used may defect or the supply voltage is not stable during WiFi operation. 

You can connect board with ypur PC via shorter USB cable or use large capacitor 220 uf or greater connect between 3.3V and GND close to board.

Even you can use ESP-12F WiFi module with this library.
