### ISSUE TITLE
How do i send location data to Firebase using NODEMCU

### ISSUE THREAD

**Issue by Prajwalk56** [mobizt/Firebase-ESP8266#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mobizt** [comment]
Send latitude and longitude as double data.

```C++
double lat = xxx.xxxxxxx;
double lng = yyy.yyyyyyy;

Firebase.setDouble(firebaseData, "path to node", lat);
Firebase.setDouble(firebaseData, "path to node", lng);

```
