### ISSUE TITLE
Help: Want to use 4 Channels Control panel with Firebase & ESP8266. 

### ISSUE THREAD

**Issue by AECPVTR** [mobizt/Firebase-ESP8266#90]
I want to use 4 Channels relay circuit with this library and ESP8266. Can you please provide full code for 4 Channels Control System?

**Comment by mobizt** [comment]
Sorry, I can't provide the example unless I can guide you with the concept.

If you mean streaming, you can set the stream path to the parent node of all children of your input channels.  

When these child node values changed, the stream event was triggered and the event path will tell you which node the value changed.

If multiples child nodes value changed at the same time, the event path will be the parent node path, you need to parse the value for every child node and compare it with its old value in this case.
