### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Mukesh7631** [mobizt/Firebase-ESP8266#95]
can I access locked data(Secured by ID and Password) from firestore by ESP8266.

**Comment by mobizt** [comment]
Yes, using database secrets will by-pass all security rules.

**Comment by mobizt** [comment]
The database secret used in the begin function as in this example https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino#L21

**Comment by Mukesh7631** [comment]
Sorry, I can't get a solution, can you give me a simple example.

**Comment by mobizt** [comment]
Ok, I get it, you're talking about Cloud Firestore and the library is for Firebase RTDB which nothing related.

**Comment by Mukesh7631** [comment]
![image](https://user-images.githubusercontent.com/62069306/76440906-931bfe00-63e4-11ea-9d9f-9f332947b4ef.png)
 
I created a database in locked mode, Now I can't access my RTDB by FIREBASE_HOST & FIREBASE_AUTH.
If I connect the same code to test mode RTDB it works nicely.
so can access  lock mode RTDB by esp8266.

**Comment by mobizt** [comment]
You're using Firebase RTDB, right?

As I said above, database secret is the way you can access the RTDB database with not related to security rules. This is the most privilege, no matter what your security rules are.

**Comment by Mukesh7631** [comment]
Thanks
