### ISSUE TITLE
HELP_ send string from Serial to Firebase

### ISSUE THREAD

**Issue by xuanbka1** [mobizt/Firebase-ESP8266#96]
Hi Mr.Mobizt !
 I have string that receive from UART, then I want to send it to FireBase. But it is not success.
here my code:

```
if (Serial.available() > 0) {

 const String  incomingByte = Serial.readString(); // read the incoming byte:
 if( Firebase.setString(firebaseData, path +"/UpdateMessage", incomingByte))
 {
   Serial.println(incomingByte);
   }
   else
   {
     Serial.println(firebaseData.errorReason());
     }
 
  }
```

and this result printed

> bad request, Invalid data; couldn't parse JSON object, array, or value.

Can You help me solve this problem !
 Thanks for your support !

**Comment by mobizt** [comment]
Your string object,  incomingByte contains some special chars that not allow in Firebase.
You should check it before sending it.

**Comment by xuanbka1** [comment]
oh! I add /CR/LF to end of UART message so i get troubles  ! Thank you so much !
